[lattice]
Lx      = 4
Ly      = 4 
Lz      = 1 # Lz is not used
orb_num = 1 # orb_num is not used
[mVMC]
sub_x   = 2
sub_y   = 2 
sub_z   = 1 # sub_z is not used
[mVMC_aft]
modpara   = "modpara.def"
directory = "aft"
